SHELL = /bin/sh
CC = gcc
CFLAGS = -Wall
SOURCECODE = main.c
EXECUTABLENAME = graph.out
LIBRARIES = -lgraph_library -lmy_library

LIBDIR = /usr/local/lib

executable_file: $(SOURCECODE)
	$(CC) $(CFLAGS) $(SOURCECODE) -o $(EXECUTABLENAME) $(LIBRARIES)

RM = rm -f

clean:
	-$(RM) $(EXECUTABLENAME)
